prometheus:
  global:
    scrape_interval: 30s
  wal_directory: C:\ProgramData\grafana-agent-wal
  configs:
    - name: default
      scrape_configs:
        - job_name: integrations/windows-exporter
          static_configs:
          - targets: ['127.0.0.1:9182']
          relabel_configs:
            - source_labels: [__address__]
              regex: '.*'
              target_label: instance
              replacement: __HOSTNAME__
      remote_write:
        - url: https://metrics-opsverse-mars.asia-south1.gcp.opsverse.cloud/api/v1/write
          basic_auth:
            username: devopsnow
            password: chang3me

loki:
  positions_directory: C:\ProgramData\grafana-agent-wal
  configs:
    - name: windows-var-log
      clients:
        - url: https://logs-opsverse-mars.asia-south1.gcp.opsverse.cloud/loki/api/v1/push
          basic_auth:
            username: devopsnow
            password: chang3me
      scrape_configs:
        # Add a job for any new dir that needs to be tailed for logs
        - job_name: windows-var-log
          static_configs:
            - labels:
                job: windows-var-log
                host: __HOSTNAME__
        - job_name: windows
          windows_events:
            use_incoming_timestamp: false
            bookmark_path: "./bookmark.xml"
            eventlog_name: "Application"
            xpath_query: '*'
            labels:
              job: windows-events
          relabel_configs:
            - source_labels: ['computer']
              target_label: 'host'
