prometheus:
  global:
    scrape_interval: 30s
  wal_directory: C:\ProgramData\grafana-agent-wal
  configs:
    - name: default
      scrape_configs:
        - job_name: integrations/windows-exporter
          static_configs:
          - targets: ['127.0.0.1:9182']
          relabel_configs:
            - source_labels: [__address__]
              regex: '.*'
              target_label: instance
              replacement: __HOSTNAME__
      remote_write:
        - url: __METRICS_URL__
          basic_auth:
            username: devopsnow
            password: __PASSWORD__

loki:
  positions_directory: C:\ProgramData\grafana-agent-wal
  configs:
    - name: windows-var-log
      clients:
        - url: __LOGS_URL__
          basic_auth:
            username: devopsnow
            password: __PASSWORD__
      scrape_configs:
        # Add a job for any new dir that needs to be tailed for logs
        - job_name: windows-var-log
          static_configs:
            - labels:
                job: windows-var-log
                host: __HOSTNAME__
        - job_name: windows
          windows_events:
            use_incoming_timestamp: false
            bookmark_path: "./bookmark.xml"
            eventlog_name: "Application"
            xpath_query: '*'
            labels:
              job: windows-events
          relabel_configs:
            - source_labels: ['computer']
              target_label: 'host'
