server:
  log_level: info

metrics:
  global:
    scrape_interval: ${SCRAPE_INTERVAL}
    remote_write:
      - url: ${OPSVERSE_METRICS_ENDPOINT}
        basic_auth:
          username: ${OPSVERSE_USERNAME}
          password: ${OPSVERSE_PASSWORD}
  configs:
    - name: default
      scrape_configs:
        - job_name: integrations/node-exporter
          static_configs:
          - targets: ['nodeexporter:9100']
          relabel_configs:
            - source_labels: [__address__]
              regex: '.*'
              target_label: instance
              replacement: ${HOST}
        - job_name: cadvisor
          static_configs:
          - targets:
            - cadvisor:8080
          relabel_configs:
            - source_labels: [__address__]
              regex: '.*'
              target_label: instance
              replacement: ${HOST}

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: "docker_scrape"
      docker_sd_configs:
        - host: unix:///var/run/docker.sock
          refresh_interval: 5s
          filters:
            - name: name
              values: ['devopsnow-agent']
      relabel_configs:
        - action: labelmap
          regex: __meta_docker_(.+)
          replacement: $1
    - job_name: var-log
      static_configs:
        - labels:
            job: varlog
            host: ${HOST}
            __path__: /var/log/*.log
    - job_name: containers
      static_configs:
        - targets:
            - localhost
          labels:
            job: containerlogs
            host: ${HOST}
            __path__: /var/lib/docker/containers/*/*log
    clients:
      - url: ${OPSVERSE_LOGS_ENDPOINT}
        basic_auth:
          username: ${OPSVERSE_USERNAME}
          password: ${OPSVERSE_PASSWORD}