server:
  log_level: info

metrics:
  global:
    scrape_interval: ${SCRAPE_INTERVAL}
    remote_write:
      - url: ${OPSVERSE_METRICS_ENDPOINT}
        basic_auth:
          username: ${OPSVERSE_USERNAME}
          password: ${OPSVERSE_PASSWORD}
  configs:
    - name: default
      scrape_configs:
        - job_name: integrations/node-exporter
          static_configs:
          - targets: ['nodeexporter:9100']
          relabel_configs:
            - source_labels: [__address__]
              regex: '.*'
              target_label: node
              replacement: ${HOST}
        - job_name: cadvisor
          static_configs:
          - targets:
            - cadvisor:8080
          relabel_configs:
            - source_labels: [__address__]
              regex: '.*'
              target_label: node
              replacement: ${HOST}
        # - job_name: mysqld-exporter
        #   static_configs:
        #   - targets:
        #     - 'mysqld-exporter:9104'
        #   relabel_configs:
        #     - source_labels: [__address__]
        #       regex: '.*'
        #       target_label: node
        #       replacement: ${HOST} 

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: "docker_scrape"
      docker_sd_configs:
        - host: unix:///var/run/docker.sock
          refresh_interval: 5s
      relabel_configs:
        - action: labelmap
          regex: __meta_docker_(.+)
          replacement: $1
    clients:
      - url: ${OPSVERSE_LOGS_ENDPOINT}
        basic_auth:
          username: ${OPSVERSE_USERNAME}
          password: ${OPSVERSE_PASSWORD}