version: "2"

services:
  agent:
    image: grafana/agent:${AGENT_VERSION}
    container_name: devopsnow-agent
    volumes:
      - /tmp/agent:/tmp/agent
      - ./agent/config:/etc/agent-config
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -config.expand-env
    ports:
      - "12345:12345"
    environment:
      - HOST=${HOST}
      - OPSVERSE_METRICS_ENDPOINT=${OPSVERSE_METRICS_ENDPOINT}
      - OPSVERSE_LOGS_ENDPOINT=${OPSVERSE_LOGS_ENDPOINT}
      - OPSVERSE_USERNAME=${OPSVERSE_USERNAME}
      - OPSVERSE_PASSWORD=${OPSVERSE_PASSWORD}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL}
    restart: unless-stopped

  nodeexporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    labels:
      org.label-schema.group: "monitoring"
 
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  #   mysqld:
  #     platform: linux/x86_64
  #     image: mysql:5.6
  #     container_name: mysqld
  #     environment:
  #       - MYSQL_ALLOW_EMPTY_PASSWORD=false
  #     volumes:
  #       - ./mysql:/etc/mysql/conf.d
  #       - ~/var/mysql:/var/lib/mysql
  #     ports:
  #       - 3306:3306

  # mysqld-exporter:
  #   platform: linux/x86_64
  #   image: quay.io/prometheus/mysqld-exporter
  #   command:
  #    --collect.info_schema.tablestats
  #   container_name: mysqld-exporter
  #   environment:
  #     - DATA_SOURCE_NAME=<user>:<password>@(mysqld:3306)/
  #   ports:
  #     - 9104:9104
  #   links:
  #     - mysqld
  #   depends_on:
  #     - mysqld