version: "2"

services:
  agent:
    image: grafana/agent:${AGENT_VERSION}
    container_name: devopsnow-agent
    volumes:
      - /tmp/agent:/tmp/agent
      - ./agent/config:/etc/agent-config
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -config.expand-env
    ports:
      - "12345:12345"
    environment:
      - HOST=${HOST}
      - OPSVERSE_METRICS_ENDPOINT=${OPSVERSE_METRICS_ENDPOINT}
      - OPSVERSE_LOGS_ENDPOINT=${OPSVERSE_LOGS_ENDPOINT}
      - OPSVERSE_USERNAME=${OPSVERSE_USERNAME}
      - OPSVERSE_PASSWORD=${OPSVERSE_PASSWORD}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL}
    restart: unless-stopped

  nodeexporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    labels:
      org.label-schema.group: "monitoring"
 
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.34.0
    command: ["/otelcontribcol", "--config=/config/otel-collector-config.yaml", "--mem-ballast-size-mib=683"]
    volumes:
      - ./otel-collector-config.yaml:/config/otel-collector-config.yaml
    ports:
      - "1777:1777"    # pprof extension
      - "8887:8888"    # Default endpoint querying metrics (prometheus)
      - "9411:9411"    # Default endpoint for Zipkin receiver.
      - "14250:14250"  # Default endpoint for Jaeger HTTP receiver.
      - "14268:14268"  # Default endpoint for Jaeger HTTO receiver.
      - "55678"        # OpenCensus receiver
      - "55680:55680"  # OTLP HTTP/2.0 legacy port
      - "55681:55681"  # OTLP HTTP/1.0 receiver
      - "4317:4317"    # Default endpoint for OTLP GRPC receiver
      - "55679:55679"  # Default endpoint for ZPages.
      - "13133"        # health_check
    deploy:
      mode: replicated
      replicas: 1
