server:
  # log_level: debug
  http_listen_port: 12345

#prometheus:
#  global:
#    scrape_interval: 30s
#  configs:
#    - name: default
#      scrape_configs:
#      remote_write:
#        - url: https://__METRICS_HOST__/api/v1/write 
#          basic_auth:
#            username: devopsnow
#            password: __PASSWORD__

loki:
  positions_directory: /tmp/
  configs:
    - name: local
      clients:
        - url: https://__LOGS_HOST__/loki/api/v1/push 
          basic_auth:
            username: devopsnow 
            password: __PASSWORD__ 
      scrape_configs:
        # Add a job for any new dir that needs to be tailed for logs
        - job_name: var-log
          static_configs:
            - labels:
                job: varlog
                host: __HOST__
                __path__: /var/log/*.log
