server:
  log_level: info

metrics:
  global:
    scrape_interval: 30s
    remote_write:
      - url: https://__METRICS_HOST__/api/v1/write
        basic_auth:
          username: devopsnow
          password: __PASSWORD__
  wal_directory: /tmp/wal/
  configs:
    - name: default
      scrape_configs:
        - job_name: file-sd-targets
          file_sd_configs:
          - files:
            - '/etc/opsverse/targets/*.json'
          relabel_configs:
            - source_labels: [__address__]
              regex: '.*'
              target_label: node
              replacement: __HOST__

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      # Add a job for any new dir that needs to be tailed for logs
      - job_name: var-log
        static_configs:
          - labels:
              job: varlog
              host: __HOST__
              __path__: /var/log/*.log
    clients:
      - url: https://__LOGS_HOST__/loki/api/v1/push
        basic_auth:
          username: devopsnow
          password: __PASSWORD__