kubestatemetrics:
  image:
    registry: registry.devopsnow.io/public
    # pullSecrets:
    #   - myRegistryKeySecretName

victoria-metrics-agent:
  image:
    repository: registry.devopsnow.io/public/victoriametrics/vmagent
  # imagePullSecrets:
  #   - myRegistrKeySecretName

daemonSet:
  image:
    repo: registry.devopsnow.io/public/grafana/agent
    # pullSecrets:
    #   - myRegistrKeySecretName

otelcollector:
  image:
    repository: registry.devopsnow.io/public/otel/opentelemetry-collector-contrib
    # pullSecrets:
    #   - myRegistrKeySecretName

k8s-event-logger:
  image:
    repository: registry.devopsnow.io/public/k8s-event-logger
  # imagePullSecrets:
  #   - myRegistrKeySecretName

postgres-exporter:
  image:
    repository: registry.devopsnow.io/public/prometheuscommunity/postgres-exporter
    # pullSecrets:
    #   - myRegistrKeySecretName

kafka-exporter:
  image:
    repository: registry.devopsnow.io/public/danielqsj/kafka-exporter

blackbox-exporter:
  image:
    registry: registry.devopsnow.io/public
    # pullSecrets:
    #   - myRegistrKeySecretName

oteloperator:
  # imagePullSecrets:
  #   - myRegistrKeySecretName
  manager:
    image:
      repository: registry.devopsnow.io/public/open-telemetry/opentelemetry-operator/opentelemetry-operator
  testFramework:
    image:
      repository: registry.devopsnow.io/public/busybox

  kubeRBACProxy:
    image:
      repository: registry.devopsnow.io/public/kubebuilder/kube-rbac-proxy

  instrumentation:
    spec:
      dotnet:
        image: registry.devopsnow.io/public/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:0.5.0
      java:
        image: registry.devopsnow.io/public/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.21.0
      nodejs:
        image: registry.devopsnow.io/public/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.34.0
      python:
        image: registry.devopsnow.io/public/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.36b0

mysql-exporter:
  image:
    repository: "registry.devopsnow.io/public/prom/mysqld-exporter"

mongodb-exporter:
  image:
    repository: registry.devopsnow.io/public/ssheehy/mongodb-exporter
  # imagePullSecrets:
  #   - myRegistrKeySecretName

elasticsearch-exporter:
  image:
    repository: registry.devopsnow.io/public/prometheuscommunity/elasticsearch-exporter
    # pullSecret: ""

redis-exporter:
  image:
    repository: registry.devopsnow.io/public/oliver006/redis_exporter
    # pullSecrets:
    #   - myRegistrKeySecretName

pyroscope-ebpf:
  image:
    repository: registry.devopsnow.io/public/pyroscope/pyroscope